version: '3.6'

volumes:
  cargo-registry:

services:
  poet2-engine:
    image: sawtooth-poet2-engine:${ISOLATION_ID}
    build:
      context: .
      dockerfile: src/core/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - .:/project/sawtooth-poet2/
    entrypoint: "bash -c \"\
        tail -f /dev/null \
        \""
